spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_kafka_tutorial
    username: spring_kafka_tutorial
    password: spring_kafka_tutorial
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: stock-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    edgareldy.springkafkatutorial: DEBUG
