spring:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  kafka:
    consumer:
      group-id: stock-service-test

management:
  endpoints:
    web:
      exposure:
        include: health

app:
  kafka:
    retry:
      max-attempts: 2
      initial-interval-ms: 10
      multiplier: 1.0
      max-interval-ms: 20
