spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_kafka_tutorial
    username: spring_kafka_tutorial
    password: spring_kafka_tutorial
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: stock-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: edgareldy.springkafkatutorial.dto.event

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    edgareldy.springkafkatutorial: DEBUG
